Repository autodesk-platform-services/aps-sdk-net, pull requests merged in 2024-10, with the labels that each got.

#99 [DAS 291] - Webhooks added HookAttributes field in hookdetails model
  webhooks/source/Model/HookDetails.gen.cs
Labels: bug

#97 Das 288 overload download method
  oss/source/Autodesk.Oss.csproj
  oss/source/custom-code/IOSSFileTransfer.cs
  oss/source/custom-code/OSSFileTransfer.cs
  oss/source/custom-code/OssClient.cs
Labels: enhancement

#104 [DAS 290] - Fix for x-ads-force-gets-ignored
  modelderivative/source/LocalMarshalling.cs
  samples/modelderivative.cs
Labels: bug

#103 [DAS-295] Fixed create Issue endpoint
  construction/issues/source/Model/AssignedToType.gen.cs
  construction/issues/source/Model/IssuePayload.gen.cs
Labels: bug

#102 [DAS 294] Update DM Client class docs
  datamanagement/source/custom-code/DataManagementClient.cs
Labels: documentation
