Repository autodesk-platform-services/aps-sdk-net, pull requests merged in 2024-09, with the labels that each got.

#79 [DAS-251]- Updated Oss sample
  samples/oss.cs
Labels: enhancement

#76 [DAS-259]-Remove Project Scope internal code
  oss/source/Autodesk.Oss.csproj
  oss/source/FileTransferException.cs
  oss/source/Http/ObjectsApi.gen.cs
  oss/source/Model/CreateSignedResource.gen.cs
  oss/source/S3ServiceApiException.cs
  oss/source/ServiceApiException.cs
  oss/source/custom-code/IOSSFileTransfer.cs
  oss/source/custom-code/OSSFileTransfer.cs
  oss/source/custom-code/OssClient.cs
Labels: enhancement

#77 [DAS-261] Define contributions guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation

#78 [DAS 260] - Mark region as obsolete in SpecifyReferences model
  modelderivative/source/Model/SpecifyReferencesPayload.gen.cs
Labels: documentation

#84 [Das 276] - add authprovider to oss
  oss/source/custom-code/OSSFileTransfer.cs
  oss/source/custom-code/OssClient.cs
  samples/oss.cs
Labels: breaking

#89 [DAS 275] - add auth provider to md
  modelderivative/source/Autodesk.ModelDerivative.csproj
  modelderivative/source/Custom code/ModelDerivativeClient.cs
  samples/modelderivative.cs
Labels: breaking

#88 [DAS-277] - Added auth provider to issues and made enums to string in results response
  construction/issues/source/Model/Results.gen.cs
  construction/issues/source/custom-code/IssuesClient.cs
  samples/issues.cs
Labels: breaking

#90 [DAS 278] - ACC Admin adding auth provider
  construction/accountadmin/source/Autodesk.Construction.AccountAdmin.csproj
  construction/accountadmin/source/ServiceApiException.cs
  construction/accountadmin/source/custom-code/AdminClient.cs
  samples/accountadmin.cs
Labels: breaking
